ru:
  time:
    seconds:
      '1': "{1} секунда"
      '2': "{1} секунды"
      '5': "{1} секунд"
    minutes:
      '1': "{1} минута"
      '2': "{1} минуты"
      '5': "{1} минут"
    hours:
      '1': "{1} час"
      '2': "{1} часа"
      '5': "{1} часов"
    days:
      '1': "{1} день"
      '2': "{1} дня"
      '5': "{1} дней"
    weeks:
      '1': "{1} неделя"
      '2': "{1} недели"
      '5': "{1} недель"
    months:
      '1': "{1} месяц"
      '2': "{1} месяца"
      '5': "{1} месяцев"
    years:
      '1': "{1} год"
      '2': "{1} года"
      '5': "{1} лет"
    permanently: навсегда
    for: на
    and: и
  cant_now: Вы не можете сделать это сейчас!
  tab_menu:
    expand: Развернуть
    settings: Настройки
    home: Домашняя страница
    scoreboard: Игроки
    admin: Админка
    close_menu: Закрыть
  scoreboard:
    title: СПИСОК ИГРОКОВ
    help: Нажмите на иконку персонажа, чтобы вызвать дополнительные опции.
  'yes': Да
  'no': Нет
  chat:
    everyone: всем
  bar_text:
    health: ЗДОРОВЬЕ
    armor: БРОНЯ
    respawn: ВОЗРОЖДЕНИЕ...
    getup: ВЫ ПОДНИМАЕТЕСЬ НА НОГИ...
  settings:
    dashboard: Меню
    theme: Тема
    adminesp: ESP Админа
    binds: Клавиши
    general: Общее
    hud: HUD
    backgroundurl: Введите ссылку на картинку для фона.
    background_color: 'Цвет фона TAB меню:'
    menu_back_color: 'Цвет панелей:'
    text_color: 'Цвет текста:'
    enable_adminesp: Включить ESP администратора
    fit_type: Выберите как следует масштабировать картинку фона.
    draw_bars: Отрисовывать полоски в HUD'е (здоровье, броня, и.т.п).
    draw_bar_text: Отрисовывать текст на полосках.
    use_tab_dash: Выберите, чтобы использовать дэшборд-меню, снимите галочку, чтобы
      использовать классический вид.
    fit:
      tiled: Плитки
      center: Центрировать
      fill: Заполнить
      fit: Подогнать размер
    draw_legs: Показывать ноги.
    toggle_auto_walk: Включить автоматический шаг
    toggle_third_person: Переключить вид от третьего лица
  commands:
    you_must_enter_command: Вы должны ввести команду!
    not_valid: "'{1}' не является командой!"
    no_access: У вас нет доступа к этой команде!
    player_invalid: "'{1}' не является игроком!"
    steamid_invalid: "'{1}' не является действительным Steam ID!"
    higher_immunity: "{1} имеет более высокий иммунитет, чем вы!"
  target_id:
    information: Нажмите 'E', чтобы посмотреть информацию.
    action: Нажмите 'E' для выполнения действия.
  hint:
    forums: Форум
    hints: Подсказки
    tab: TAB
    commands: Команды
    bugs: Баги
    forums_text: Зайдите на форум TeslaCloud, чтобы получить поддержку, скачать плагины\nи
      просто общаться с другими пользователями Flux!
    hints_text: Эти подсказки можно выключить через меню настроек.\nПравда не в этой
      версии.
    tab_text: Нажмите кнопку показа счёта (по умолчанию TAB), чтобы открыть меню.
    commands_text: Начните вводить команду в чат, чтобы увидеть её описание\nи документацию
      по использованию.
    bugs_text: Нашли баг? У вас есть идея, которую мы могли бы воплотить в Flux?\nПосетите
      наш форум TeslaCloud.net и расскажите нам об этом!
  player_message:
    died: ВЫ МЕРТВЫ
    respawn: ВОЗРОЖДЕНИЕ ЧЕРЕЗ {1}
  loading:
    schema: Загрузка схемы и плагинов...
    local_player: Инициализация...
    shared: Получение данных с сервера...
  intro:
    skip: Нажмите любую клавишу...
